question_data = [{"category": "Entertainment: Video Games", "type": "boolean", "difficulty": "medium",
                  "question": "Amazon acquired Twitch in August 2014 for $970 million dollars.",
                  "correct_answer": "True", "incorrect_answers": ["False"]},
                 {"category": "Entertainment: Video Games", "type": "boolean", "difficulty": "hard",
                  "question": "The first &quot;Metal Gear&quot; game was released for the PlayStation 1.",
                  "correct_answer": "False", "incorrect_answers": ["True"]},
                 {"category": "Entertainment: Video Games", "type": "boolean", "difficulty": "medium",
                  "question": "In &quot;Team Fortress 2&quot;, the &quot;Bill&#039;s Hat&quot; is a reference to the game &quot;Dota 2&quot;.",
                  "correct_answer": "False", "incorrect_answers": ["True"]},
                 {"category": "Entertainment: Video Games", "type": "boolean", "difficulty": "medium",
                  "question": "In Half-Life 2, if you play the zombies&#039; speech in reverse, they actually speak coherent English.",
                  "correct_answer": "True", "incorrect_answers": ["False"]},
                 {"category": "Entertainment: Video Games", "type": "boolean", "difficulty": "easy",
                  "question": "The ultimate phrase used by Pharah from Overwatch is: &quot;Justice rains from above!&quot;",
                  "correct_answer": "True", "incorrect_answers": ["False"]},
                 {"category": "Entertainment: Video Games", "type": "boolean", "difficulty": "easy",
                  "question": "The end credits sequence in Grand Theft Auto 5 is over half an hour long.",
                  "correct_answer": "True", "incorrect_answers": ["False"]},
                 {"category": "Entertainment: Video Games", "type": "boolean", "difficulty": "medium",
                  "question": "In Monster Hunter Generations, guild style is a type of hunting style.",
                  "correct_answer": "True", "incorrect_answers": ["False"]},
                 {"category": "Entertainment: Video Games", "type": "boolean", "difficulty": "medium",
                  "question": "In &quot;Call Of Duty: World At War&quot;, the first appearance of the &quot;PPSH-41&quot; in &quot;Zombies&quot; was in the map &quot;Der Riese&quot;.",
                  "correct_answer": "False", "incorrect_answers": ["True"]},
                 {"category": "Entertainment: Video Games", "type": "boolean", "difficulty": "medium",
                  "question": "The Fiat Multipla is a drivable car in &quot;Forza Horizon 3&quot;.",
                  "correct_answer": "False", "incorrect_answers": ["True"]},
                 {"category": "Entertainment: Video Games", "type": "boolean", "difficulty": "medium",
                  "question": "&quot;Return to Castle Wolfenstein&quot; was the only game of the Wolfenstein series where you don&#039;t play as William &quot;B.J.&quot; Blazkowicz.",
                  "correct_answer": "False", "incorrect_answers": ["True"]},
                 {"category": "Entertainment: Video Games", "type": "boolean", "difficulty": "medium",
                  "question": "During pre-production of &quot;Super Mario Bros.&quot;, Mario originally was meant to shoot bullets.",
                  "correct_answer": "True", "incorrect_answers": ["False"]},
                 {"category": "Entertainment: Video Games", "type": "boolean", "difficulty": "medium",
                  "question": "In &quot;Resident Evil&quot;, only Chris has access to the grenade launcher.",
                  "correct_answer": "False", "incorrect_answers": ["True"]}]
